### ISSUE TITLE
Encoding or compressing stuck at 'extracting metadata'

### ISSUE THREAD

**Issue by vasusen-code** [vasusen-code/VIDEOconvertor#21]
Well idk why is this happening and not able to figure it out for now, will fix soon as i get a solution.

**Comment by vasusen-code** [comment]
Fixed

**Comment by Baport** [comment]
still having stuck in extracting metadata using main branch. Pls have a look

**Comment by SoloLeveling7seven** [comment]
Please help same thing happening stuck on metadata
