### ISSUE TITLE
how to fix this error?

### ISSUE THREAD

**Issue by DarkDevil069** [vasusen-code/VIDEOconvertor#36]
![Screenshot (54)](https://user-images.githubusercontent.com/101288269/160244010-f4498aeb-4982-49f8-b2a7-8bd70431cd2f.png)

**Comment by vasusen-code** [comment]
Are you still facing the issue?

**Comment by DarkDevil069** [comment]
Yes. It just doesn't wanna work. I have tried redeploying too, but no good.

**Comment by Tellyfun** [comment]
> Bro Install Ffmpeg
