### ISSUE TITLE
gdrive support

### ISSUE THREAD

**Issue by askfriends** [vasusen-code/VIDEOconvertor#5]
will u consider adding gdrive support?
so that we can convert/trim gdrive files

**Comment by vasusen-code** [comment]
> will u consider adding gdrive support? so that we can convert/trim gdrive files

Ummm but there are many fast uploaders like anydl and urluploaderx which can upload drive files in seconds on telegram , which can later be processed in the convertor.

**Comment by askfriends** [comment]
> > will u consider adding gdrive support? so that we can convert/trim gdrive files
> 
> Ummm but there are many fast uploaders like anydl and urluploaderx which can upload drive files in seconds on telegram , which can later be processed in the convertor.

Yes you are right but there isnt any bot which actually merge these two functions, thats why i asked if you could do it than it will be very handy and helpful.

**Comment by vasusen-code** [comment]
Fine, will add soon. For now i added permanent thumbnail nd updated repo.

**Comment by askfriends** [comment]
> Fine, will add soon. For now i added permanent thumbnail nd updated repo.

Thanks and will be waiting for that update.
